name: Test Go

on:
  pull_request:

jobs:
  test:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go test ./...
      - run: go build
      - uses: golangci/golangci-lint-action@v3
