name: Test Go

on:
  pull_request:

jobs:
  test:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go test ./... -timeout 60s
      - run: go build
      - uses: golangci/golangci-lint-action@v3
